#!/bin/sh
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<meta charset=\"utf8\" />"
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\" />"
echo "<title>$TITLE</title>"
echo "<style>"
echo "$STYLE"
echo "</style>"
echo "</head>"
echo "<body>"
echo "$BODY"
echo "</body>"
echo "</html>"
